# Generated by Django 4.0.5 on 2022-06-15 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyAbuse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=255, verbose_name='Название компании')),
                ('abuse_type', models.CharField(max_length=255, verbose_name='Категория жалобы')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Комментарий пользователя')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Жалоба',
                'verbose_name_plural': 'Жалобы',
                'db_table': 'company_abuse',
            },
        ),
        migrations.CreateModel(
            name='CompanyApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Имя клиента')),
                ('phone', models.CharField(max_length=255, verbose_name='Телефон клиента')),
                ('company_name', models.CharField(max_length=255, verbose_name='Название компании')),
                ('issue_type', models.CharField(max_length=255, verbose_name='Тип техники')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание поломки')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Заявка компании',
                'verbose_name_plural': 'Заявки компаний',
                'db_table': 'company_applications',
            },
        ),
        migrations.CreateModel(
            name='RepairApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Имя')),
                ('phone', models.CharField(max_length=255, verbose_name='Телефон')),
                ('issue_type', models.CharField(max_length=255, verbose_name='Что сломалось')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Заявка на ремонт',
                'verbose_name_plural': 'Заявки на ремонт',
                'db_table': 'repair_applications',
            },
        ),
    ]
