# Generated by Django 3.0.2 on 2020-01-20 13:10

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True, help_text='Опубликована на сайте', verbose_name='Активная')),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок страницы')),
                ('slug', models.SlugField(help_text='e.g.: about-us (max 100 chars), получим https://monolit.site/about-us/', max_length=100, unique=True, verbose_name='URL адрес')),
                ('body', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Текст')),
            ],
            options={
                'verbose_name': 'Страница',
                'verbose_name_plural': 'Страницы',
            },
        ),
    ]
