# Generated by Django 3.0.2 on 2020-01-20 13:10

import apps.news.models.actions
import apps.news.models.news
import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import imagekit.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('realty', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Actions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True, help_text='Опубликована на сайте', verbose_name='Активная')),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок акции')),
                ('date_start', models.DateField(default=django.utils.timezone.now, verbose_name='Дата начала акции')),
                ('date_end', models.DateField(blank=True, null=True, verbose_name='Дата окончания акции')),
                ('description', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Описание акции')),
                ('partners_title', models.CharField(blank=True, max_length=255, null=True, verbose_name='Заголовок для партнеров')),
                ('image_card', imagekit.models.fields.ProcessedImageField(blank=True, null=True, upload_to=apps.news.models.actions.actions_image_upload_path, verbose_name='Изображение для карточки')),
                ('image_detail', models.ImageField(blank=True, null=True, upload_to=apps.news.models.actions.actions_image_upload_path, verbose_name='Изображение для страницы')),
            ],
            options={
                'verbose_name': 'Акция',
                'verbose_name_plural': 'Акции',
            },
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True, help_text='Опубликована на сайте', verbose_name='Активная')),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок новости')),
                ('date', models.DateField(default=django.utils.timezone.now, verbose_name='Дата')),
                ('main_image', models.ImageField(blank=True, null=True, upload_to=apps.news.models.news.main_image_upload_path, verbose_name='Главное изображение')),
                ('body', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Текст новости')),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Новость',
                'verbose_name_plural': 'Новости',
            },
        ),
        migrations.CreateModel(
            name='NewsCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Имя категории')),
            ],
            options={
                'verbose_name': 'Новостная категория',
                'verbose_name_plural': 'Категории новостей',
            },
        ),
        migrations.CreateModel(
            name='NewsImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to=apps.news.models.news.image_upload_path, verbose_name='Изображение')),
                ('news', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='news.News', verbose_name='Новость')),
            ],
            options={
                'verbose_name': 'Изображение',
                'verbose_name_plural': 'Изображения',
            },
        ),
        migrations.AddField(
            model_name='news',
            name='category',
            field=models.ManyToManyField(blank=True, to='news.NewsCategory', verbose_name='Категории новости'),
        ),
        migrations.AddField(
            model_name='news',
            name='object',
            field=models.ManyToManyField(blank=True, help_text='Относится ли данная новость к Объекту(ам) недвижимости? Если нет, то оставьте пустым', to='realty.Object', verbose_name='Объект(ы)'),
        ),
        migrations.CreateModel(
            name='ActionsPartner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название партнера')),
                ('logo', models.ImageField(blank=True, null=True, upload_to=apps.news.models.actions.actions_partner_logo_upload_path, verbose_name='Логотип партнера акции')),
                ('site_url', models.URLField(blank=True, help_text='Url сайта партнера', null=True, verbose_name='Сайт партнера')),
                ('action', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='news.Actions', verbose_name='Акция')),
            ],
            options={
                'verbose_name': 'Партнер акции',
                'verbose_name_plural': 'Партнеры акций',
            },
        ),
    ]
