# Generated by Django 4.0.5 on 2022-06-19 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0004_alter_brand_name_alter_category_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='brands',
            field=models.ManyToManyField(blank=True, db_index=True, related_name='companies', to='company.brand', verbose_name='Бренды'),
        ),
    ]
