# Generated by Django 3.0.2 on 2020-01-31 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realty', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='object',
            name='yandex_map',
            field=models.TextField(blank=True, help_text='Создайте и карту сметками в Конструкторе Яндекс Карт https://yandex.ru/map-constructor/ и добавьте в данное поле код', null=True, verbose_name='Карта из Яндекса'),
        ),
    ]
