# Generated by Django 3.0.2 on 2020-01-31 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realty', '0002_object_yandex_map'),
    ]

    operations = [
        migrations.AlterField(
            model_name='object',
            name='yandex_map',
            field=models.TextField(blank=True, help_text='Создайте и карту сметками в Конструкторе Яндекс Карт https://yandex.ru/map-constructor/ и добавьте в данное поле код JavaScript код с параметром scroll=false', null=True, verbose_name='Карта из Яндекса'),
        ),
    ]
